<?php

/**
 * Implementation of hook_views_api().
 */
function json_views_views_api() {
  return array(
    'api'  => 2,
    'path' => drupal_get_path('module', 'json_views'),
  );
}

//tools stolen from exhibit

function json_views_json($items, $types = NULL, $properties = NULL) {
  return json_views_compact_item(array(
    'types'      => $types,
    'properties' => $properties,
    'items'      => $items,
  ));
}

function json_views_compact_item($item) {
  foreach ($item as $k => $v) {
    if (is_null($v)) {
      unset($item[$k]);
    }
  }
  return $item;
}